services:

  singbox-sub-manager:

    build:
      context: .

      dockerfile: Dockerfile


    container_name:

      singbox-sub-manager



    restart:

      unless-stopped



    ports:

      - "8000:8000"



    environment:

      DATA_DIR: /data

      ADMIN_KEY: change-this-key

      APP_NAME: singbox-sub-manager

      VERSION: 1.0.0



    volumes:

      - ./data:/data
